# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Progress Athens Foundation
email: progressathens@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Progress Athens Foundation is dedicated to improving the quality of life in
  Athens, Wisconsin and the surrounding area. We are a non-profit organization
  that provides grants to local organizations and individuals to help them achieve
  their goals.
  Progress Athens Foundation, Inc.'s mission is to preserve and enhance the
  Athens area for current and future generations.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://progressathens.org" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: ProgressAthensFoundation

address_name: Progress Athens Foundation, Inc.
street_address: P.O. Box 147
city: Athens
state: WI
zip_code: 54411

plugins:
  - jekyll-seo-tag

collections:
  about:
    output: true
  board_members:
    output: true
  grants:
    output: true
  recipients:
    output: true
